:icons: font
:source-highlighter: prettify
:doctype: book
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

== Description:

Introduction of new domain without explicit projection or any other explicit plumbing like repository, service, or endpoint

== Goals:

- Demonstrate the simplest type of domain introduction
- Show full lifecycle support (json in/out) for the endpoint API
- Builds On : xref:concepts/00100-productExtensionOnly/README.adoc[00100-productExtensionOnly]

== Key Steps:

[NOTE]
====
`META-INF/spring.factories` is generated automatically as part of the tutorial. However, in a real implementation, this file must be explicitly created and populated.
====

[NOTE]
====
Existing implementations will continue to depend on starter project liquibase support to emit client domain customization changelogs (e.g. `UtilitiesIT` usage). In the future, liquibase changelog generation support will be included as part of the maven build for development projects at large (similar to how it's done in the tutorial concepts).
====

- Create spring boot autoconfiguration class `NewDomainOnly`, which will be referenced from META-INF/spring.factories
- Create new JPA repository domain class (`ChargingStation`)
- Declare `@EnableJpaTrackableFlow` for the autoconfiguration class to setup the lifecycle plumbing for the new domain class
- Declare `@AutoConfigureBefore` for the autoconfiguration class to scan the new domain class before JPA processing
