== Description:

Simple extension of `JpaProduct` adding more complex field types, including collections and maps. The complex types use JPA converters to persist the complex structure as JSON. This example still leverages auto projection and does not declare an explicit extending projection type.

== Goals:

- Demonstrate more complex field type
- Demonstrate interaction with `Projection` interface to expose complex structures for editing
- Show full lifecycle support (json in/out) for the endpoint API
- Show supporting admin customization
- Builds On : _00100-productExtensionOnly_

== Key Steps:

[NOTE]
====
`META-INF/spring.factories` is generated automatically as part of the tutorial. However, in a real implementation, this file must be explicitly created and populated.
====

[NOTE]
====
Existing implementations will continue to depend on starter project liquibase support to emit client domain customization changelogs (e.g. `UtilitiesIT` usage). In the future, liquibase changelog generation support will be included as part of the maven build for development projects at large (similar to how it's done in the tutorial concepts).
====

- Create spring boot autoconfiguration class `ProductExtensionComplexFieldJson`, which will be referenced from META-INF/spring.factories
- Create `MyAutoCoProduct` repository domain class extending Broadleaf's `JpaProduct`
- Implement new collection fields in `MyAutoCoProduct`
- Use the `@Convert` annotation on the collection fields to reference JPA converters for JSON/Collection conversion
- Add `JpaEntityScan` annotation to autoconfiguration class above for new extended entity class
- Add `AutoConfigureBefore(..)` annotation to autoconfiguration class above to make sure the entity reference is scanned before JPA processing
