:icons: font
:source-highlighter: prettify
:doctype: book
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

== Description:

Adds a new repository implementation fragment overriding out-of-the-box behavior of JpaTrackableRepository

== Goals:

- Show concrete fragment contribution example overriding JpaTrackableRepository methods for JpaProductRepository
- Demonstrate the use of JpaTrackableRepositoryDelegateSupplier to use in the fragment for extension via composition
- Builds On : _0700-repositoryCustomizationOverride, 00200-productExtensionComplexFieldJson_

== Key Steps:

include::../doc/caveats.adoc

- Create spring boot autoconfiguration class `RepositoryCustomizationOverride`, which will be referenced from META-INF/spring.factories
- Declare the `JpaTrackableRepositoryDelegateHelper` bean for access to the Broadleaf repository
- Create a new concrete repository fragment (DefaultMyAutoCoProductRepositoryOverride) and an interface for the fragment
- Override (or add new) methods in the fragment
- Declare a bean for the concrete fragment in the autoconfiguration class
- Declare a `RepositoryContribution` bean in the autoconfiguration class, registering the new fragment with Broadleaf's out-of-the-box repository
