:icons: font
:source-highlighter: prettify
:doctype: book
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

== Description:

Business logic customization that leverages a customized repository and extended domain with auto projection

== Goals:

- Show DefaultProductService call the customized repository to search by a new extended field
- Demonstrate how to use the Projection interface to interact with the service API
- Builds On : _00800-repositoryCustomizationContribution_

== Key Steps:

include::../doc/caveats.adoc

- Create spring boot autoconfiguration class `BusinessLogicCustomizationAutoProjection`, which will be referenced from META-INF/spring.factories
- Create extension (`MyAutoCoProductService`) of `DefaultProductService` adding a new method
- Use the `@Component` annotation on the extended service
- Declare the `@ComponentScan` annotation to the autoconfiguration class (avoid the larger constructor injection requirements of declaring a bean for the service extension)
