:icons: font
:source-highlighter: prettify
:doctype: book
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

== Description:

Introduction of new domain including complex field structures

== Goals:

- Demonstrate domain introduction with embedded json collection fields
- Demonstrate domain introduction with nested JPA OneToMany collection fields
- Builds On : _01500-newDomain_

== Key Steps:

[NOTE]
====
`META-INF/spring.factories` is generated automatically as part of the tutorial. However, in a real implementation, this file must be explicitly created and populated.
====

[NOTE]
====
Existing implementations will continue to depend on starter project liquibase support to emit client domain customization changelogs (e.g. `UtilitiesIT` usage). In the future, liquibase changelog generation support will be included as part of the maven build for development projects at large (similar to how it's done in the tutorial concepts).
====

- Create spring boot autoconfiguration class `NewDomainComplexField`, which will be referenced from META-INF/spring.factories
- Create new JPA repository domain class (`ChargingStation`)
- Create a new JPA repository domain class to serve as new collection field member (`Charger`)
- Add `@ProjectionPostConvert` annotated method to `Charger` to handle the bi-directional reference back to the parent entity
- Create a new simple POJO class to serve as JSON converted collection field member (`Pricing`)
- Add new collection fields to `ChargingStation`
- Add JPA converter on the `Pricing` related collection field in `ChargingStation`
- Declare `@EnableJpaTrackableFlow` for the autoconfiguration class to setup the lifecycle plumbing for the new domain class
- Declare `@AutoConfigureBefore` for the autoconfiguration class to scan the new domain class before JPA processing
